/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void showingQuoteTest() throws IOException {
       Quote q1=new Quote(new String[]{"nithing"},"rawan","5 like","anything");
       assertNotNull(q1);
    }
    @Test void appHasAGreeting() {
        App classUnderTest = new App();

    }
}
