/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

public class App {

    public static void showingQuote(String path) throws IOException {

        try {

            Gson gson = new Gson();
            // create a reader
            BufferedReader reader = new BufferedReader(new FileReader(path));

            //Quote quote = gson.fromJson(reader,Quote.class);
            ArrayList<Quote> quote = new Gson().fromJson(reader, new TypeToken<ArrayList<Quote>>() {}.getType());
            //System.out.println(quote.size());
            int rand = (int) (Math.random()*quote.size());
            System.out.println(rand);
            // print users
            System.out.println(quote.get(rand));
            //quote.forEach(System.out::println);

            // close reader
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("error");
        }

    }

    public static void main(String[] args) throws IOException{
        System.out.println("random quote from lab 8");
       showingQuote("app/src/main/java/quotes/q.json");
        String apiURL="https://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        try{
            Gson gson=new Gson();
            URL url =new URL(apiURL);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
            int status=connection.getResponseCode();
            if(status==200){
                InputStream inputStream = connection.getInputStream();
                InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
                BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
                //read from api and store it in object
                ApiQuote apiQuote=new Gson().fromJson(bufferedReader,ApiQuote.class);
                System.out.println("from API");
                System.out.println(apiQuote);

                //store api quote in file
                BufferedWriter bw = new BufferedWriter(new FileWriter("app/src/main/java/quotes/fromApi.json" , false));
                String newQuotes = gson.toJson(apiQuote);
                bw.write(newQuotes);
                bw.close();

            }else{
                System.out.println("An error occurred with status "+status);
            }
            connection.disconnect();



        }catch (Exception e) {
            System.out.println("from file :");
            showingQuote("app/src/main/java/quotes/q.json");
        }

    }
}
