/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

public class App {

    public static void showingQuote(String path) throws IOException {

        try {

            Gson gson = new Gson();
            // create a reader
            BufferedReader reader = new BufferedReader(new FileReader(path));

            //Quote quote = gson.fromJson(reader,Quote.class);
            ArrayList<Quote> quote = new Gson().fromJson(reader, new TypeToken<ArrayList<Quote>>() {}.getType());
            //System.out.println(quote.size());
            int rand = (int) (Math.random()*quote.size());
            System.out.println(rand);
            // print users
            System.out.println(quote.get(rand));
            //quote.forEach(System.out::println);

            // close reader
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("error");
        }

    }

    public static void main(String[] args) throws IOException{
        showingQuote("app/src/main/java/quotes/q.json");

    }
}
